#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi


# Redirect output to stderr.
exec 1>&2


# If there are whitespace errors, print the offending file names and fail.
exec find . -name \*.sh -exec shellcheck {} \;
